general {
    hide_cursor = true
    grace = 2
    no_fade_in = false
}

background {
    monitor =
    path = /home/adomas/netrinti/wallpaper_green.png
    blur_passes = 3
    blur_size = 8
    brightness = 0.55
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.25
    dots_spacing = 0.25
    dots_center = true
    outer_color = rgb(cba6f7)
    inner_color = rgb(11111b)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = "Password..."
    fail_text = "Wrong password"
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(cdd6f4)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B"
    color = rgb(a6adc8)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 90
    halign = center
    valign = center
}
